package com.uncc.inclass02;

public class AppConstant {
    public static final int LOGIN_CODE = 100;
    public static final int VIEW_MAP = 150;
    public static final int SIGNUP_CODE = 200;
    public static final int DASHBOARD_CODE = 300;
    public static final int CHATROOM_CODE = 400;
    public static final int REQUEST_RIDE_CODE = 500;
    public static final int SELECT_DRIVER_CODE = 600;
    public static final int PICKUP_AUTOCOMPLETE = 700;
    public static final int DROPOFF_AUTOCOMPLETE = 800;
    public static final int REQUEST_LOC_CODE = 900;
    public static final String MY_PROFILE = "MY_PROFILE";
    public static final String CHAT = "CHAT";
    public static final String CHAT_USERS = "CHAT_USERS";
    public static final String CHATROOM_DB_KEY = "chatrooms";
    public static final String USER_DB_KEY = "userProfiles";
    public static final String RIDE_DB_KEY = "rides";
    public static final String DRIVER_DB_KEY = "drivers";
    public static final String CHATROOM_ID = "id";
    public static final String CHATROOM_NAME = "name";
    public static final String CURR_USERS = "people";
    public static final String MESSAGES = "messages";
    public static final String TIME_FORMAT = "yyyy-MM-dd HH:mm:ss";
    public static final String USER_LIKING = "userLiking";
    public static final String TEXT_TYPE = "TEXT";
    public static final String LOC_REQ_TYPE = "LOC_REQ";
    public static final String RIDE_REQ_TYPE = "RIDE_REQ";
    public static final String CONFIRM_DRIVER_TYPE = "CONFIRM_DRIVER_TYPE";
    public static final String TRIP_COMPLETE = "complete";
    public static final String TRIP_ACTIVE = "active";
    public static final String RIDE_REQ_RESULT = "RIDE_REQ_RESULT";
    public static final String LOC_REQ_RESULT = "LOC_REQ_RESULT";
    public static final String TRIP_ID_RESULT = "TRIP_ID_RESULT";
    public static final String TRIP_ID = "TRIP_ID";
    public static final String WRONG_TRIP_ID = "WRONG_TRIP_ID";
    public static final String API_KEY = "AIzaSyCjQlEN9SKDCtC30zy7grp-lyhPjEv792Q";
    public static final int PERMISSION_REQUEST_READ_FINE_LOCATION = 1;
    public static final String LOCATION_TEXT = "LOCATION_TEXT";
    public static final String MAP_TO_SHOW_RIDER = "MAP_TO_SHOW_RIDER";
    public static final String DRIVER_ID = "DRIVER_ID";
    public static final String DRIVER_CURRENT_LOCATION = "currLoc";
    public static final String DRIVER_CURRENT_LatLoc = "latLoc";
    public static final String DRIVER_CURRENT_LonLoc = "longLoc";
}
